# -*- coding: utf-8 -*-
"""Task 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M6JesO1ATMAiaYxBbG_4bb-d2EJITlWs
"""

GRADE_POINTS = {
    'A+': 4.0,
    'A': 4.0,
    'A-': 3.7,
    'B+': 3.3,
    'B': 3.0,
    'B-': 2.7,
    'C+': 2.3,
    'C': 2.0,
    'C-': 1.7,
    'F': 0.0
}

def calculate_weighted_gpa(grades):

    total_points = 0
    total_credits = 0

    for grade, credit in grades:
        point = GRADE_POINTS.get(grade.upper(), None)
        if point is None:
            print(f"Warning: Invalid grade '{grade}' skipped.")
            continue
        total_points += point * credit
        total_credits += credit

    if total_credits == 0:
        return 0.0

    gpa = total_points / total_credits
    return round(gpa, 2)

def print_gpa_summary(student_name, gpa):

    print(f"🎓 Student {student_name} has GPA: {gpa:.2f}")


if __name__ == "__main__":
    student_name = "Hasham"
    grade_list = [('A', 3), ('B+', 4), ('C', 2)]


    final_gpa = calculate_weighted_gpa(grades=grade_list)
    print_gpa_summary(student_name=student_name, gpa=final_gpa)