# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KvDUKt1UyIfILQHMIi23Blcf7_b9ZrC0
"""

sentence = input("Enter a sentence: ")
words_list = sentence.split()

print("List of words:", words_list)

joined_sentence = ' - '.join(words_list)

print("Joined sentence with dashes:", joined_sentence)


my_name = ("Hasham", "Asim")

print("First Name:", my_name[0])
print("Last Name:", my_name[1])