# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sO13x1valuvlegqQ60sVfLgdl73H1eQD
"""

#  Task: String Slicing & Simple Calculator


full_name = input("Enter your full name (First Last): ")


space_index = full_name.find(" ")
first_name = full_name[:space_index]
last_name = full_name[space_index + 1:]

print(f"\n👤 First Name: {first_name}")
print(f"👤 Last Name: {last_name}")


num1 = float(input("\nEnter the first number: "))
num2 = float(input("Enter the second number: "))

add = num1 + num2
sub = num1 - num2
mul = num1 * num2
div = num1 / num2 if num2 != 0 else "Cannot divide by zero"

print("\n🧮 Calculation Results:")
print(f"Addition: {num1} + {num2} = {add}")
print(f"Subtraction: {num1} - {num2} = {sub}")
print(f"Multiplication: {num1} * {num2} = {mul}")
print(f"Division: {num1} / {num2} = {div}")