# -*- coding: utf-8 -*-
"""Task 17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BuuPOzoO3FiMs-WclZhgmAoQr-5EIj5q
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile weather_client.py
# import requests
# 
# class APIKeyMissingError(Exception):
#     """Custom exception for missing API key."""
#     pass
# 
# def fetch_weather(city, api_key):
#     if not api_key:
#         raise APIKeyMissingError("API key is missing.")
# 
#     url = f"http://api.weatherapi.com/v1/current.json?key={api_key}&q={city}"
# 
#     try:
#         response = requests.get(url)
#         response.raise_for_status()
#         return response.json()
#     except requests.exceptions.RequestException as e:
#         raise RuntimeError(f"Failed to fetch weather data: {e}")
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile test_weather_client.py
# import unittest
# from unittest.mock import patch
# from weather_client import fetch_weather, APIKeyMissingError
# 
# class TestWeatherClient(unittest.TestCase):
# 
#     def test_missing_api_key(self):
#         with self.assertRaises(APIKeyMissingError):
#             fetch_weather("London", "")
# 
#     @patch('weather_client.requests.get')
#     def test_valid_response(self, mock_get):
#         mock_response = mock_get.return_value
#         mock_response.raise_for_status.return_value = None
#         mock_response.json.return_value = {
#             "location": {"name": "London"},
#             "current": {"temp_c": 25}
#         }
# 
#         result = fetch_weather("London", "dummy_key")
#         self.assertEqual(result["location"]["name"], "London")
#         self.assertEqual(result["current"]["temp_c"], 25)
# 
# if __name__ == '__main__':
#     unittest.main(argv=[''], exit=False)
#

!python3 test_weather_client.py