# -*- coding: utf-8 -*-
"""Task8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11lCIfJ2UUKNAJ5qgphc6e-0fbHEhGx39
"""

# Dynamic Contact Book - Day 8 Task
# ProSensia Internship

def is_valid_email(email):
    return "@" in email and "." in email

def manage_contact_book():
    contacts = {}

    while True:
        print("\n--- Contact Book Menu ---")
        print("1. Add Contact")
        print("2. Update Contact")
        print("3. Retrieve Contact")
        print("4. View All Contacts")
        print("5. Exit")

        choice = input("Enter your choice (1-5): ")

        if choice == '1':
            name = input("Enter name: ").title()
            if name in contacts:
                print("Contact already exists!")
            else:
                phone = input("Enter phone: ")
                email = input("Enter email: ")
                if is_valid_email(email):
                    contacts[name] = {"phone": phone, "email": email}
                    print("Contact added.")
                else:
                    print("Invalid email. Must contain '@' and '.'")

        elif choice == '2':
            name = input("Enter name to update: ").title()
            if name in contacts:
                print("What do you want to update?")
                print("1. Phone")
                print("2. Email")
                update_choice = input("Enter choice: ")

                if update_choice == '1':
                    new_phone = input("Enter new phone: ")
                    contacts[name]['phone'] = new_phone
                    print("Phone updated.")
                elif update_choice == '2':
                    new_email = input("Enter new email: ")
                    if is_valid_email(new_email):
                        contacts[name]['email'] = new_email
                        print("Email updated.")
                    else:
                        print("Invalid email format.")
                else:
                    print("Invalid option.")
            else:
                print("Contact not found.")

        elif choice == '3':
            name = input("Enter name to search: ").title()
            if name in contacts:
                print(f"{name} → Phone: {contacts[name]['phone']}, Email: {contacts[name]['email']}")
            else:
                print("Contact not found.")

        elif choice == '4':
            if not contacts:
                print("No contacts to show.")
            else:
                print("\n--- All Contacts ---")
                for name, info in contacts.items():
                    print(f"{name} → Phone: {info['phone']}, Email: {info['email']}")

        elif choice == '5':
            print("Exiting Contact Book. Goodbye!")
            break

        else:
            print("Invalid choice. Please enter a number from 1 to 5.")


manage_contact_book()