# -*- coding: utf-8 -*-
"""Task5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KvDUKt1UyIfILQHMIi23Blcf7_b9ZrC0
"""

print("my name is hasham")