# -*- coding: utf-8 -*-
"""Task13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bVCwjcD6V_0yR-ep8vEAliReeDGvYNzt
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

if not os.path.exists("plots"):
    os.makedirs("plots")

df=pd.read_csv("data.csv")

display(df)

plt.figure(figsize=(10, 5))
plt.plot(df["Month"], df["Revenue"], marker='o', color='green')
plt.title("Monthly Revenue")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("plots/Line_Chart.png")
plt.close()
print("Line chart saved as plots/Line_Chart.png")


plt.figure(figsize=(8, 5))
plt.bar(df["Product"], df["Sales"], color='skyblue')
plt.title("Sales by Product")
plt.xlabel("Product")
plt.ylabel("Sales")
plt.tight_layout()
plt.savefig("plots/Bar_Chart.png")
plt.close()
print("Bar chart saved as plots/Bar_Chart.png")


plt.figure(figsize=(7, 7))
top_regions = df.groupby("Region")["MarketShare"].sum().reset_index()
plt.pie(top_regions["MarketShare"], labels=top_regions["Region"], autopct='%1.1f%%', startangle=140)
plt.title("Market Share by Region")
plt.tight_layout()
plt.savefig("plots/Pie_Chart.png")
plt.close()
print("Pie chart saved as plots/Pie_Chart.png")

plt.figure(figsize=(10, 7))
corr = df[["Revenue", "Sales", "MarketShare"]].corr()
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.tight_layout()
plt.savefig("plots/Heatmap.png")
plt.close()
print("Heatmap saved as plots/Heatmap.png")

summary = df.describe()
summary_path = "plots/Summary_Report.txt"
with open(summary_path, "w") as f:
    f.write("Data Summary:\n\n")
    f.write(summary.to_string())
print("Summary report saved as plots/Summary_Report.txt")

print("\nAll tasks completed successfully.")