# -*- coding: utf-8 -*-
"""Task12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u70puU-GJ8oErnIMDfHzoBvkJpGPChO7
"""

import requests

def fetch_exchange_rates(api_url):
    try:
        response = requests.get(api_url)
        response.raise_for_status()
        return response.json()
    except Exception as e:
        print(f"[Error] API fetch failed: {e}")
        return None

def extract_selected_rates(data, target_currencies):
    try:
        all_rates = data.get("rates", {})
        base_currency = data.get("base", "USD")
        selected_rates = {}

        for currency in target_currencies:
            selected_rates[currency] = all_rates.get(currency, "N/A")

        return base_currency, selected_rates
    except Exception as e:
        print(f"[Error] Could not extract rates: {e}")
        return "USD", {}

def display_and_save_report(base, rates, file_name="exchange_rate_report.txt"):
    print(f"\nExchange Rates (Base: {base})")
    print("-----------------------------")
    lines = []
    for cur, rate in rates.items():
        line = f"{base} → {cur}: {rate}"
        print(line)
        lines.append(line)

    try:
        with open(file_name, "w") as f:
            f.write(f"Exchange Rates (Base: {base})\n")
            f.write("-----------------------------\n")
            for l in lines:
                f.write(l + "\n")
        print(f"\nReport saved to: {file_name}")
    except Exception as e:
        print(f"[Error] Failed to write report: {e}")

def main():
    api_url = "https://api.exchangerate-api.com/v4/latest/USD"
    wanted = ["PKR", "EUR", "GBP", "INR", "CAD", "AUD"]

    print("Fetching exchange rates for:", ', '.join(wanted))

    data = fetch_exchange_rates(api_url)
    if data:
        base, selected = extract_selected_rates(data, wanted)
        display_and_save_report(base, selected)

if __name__ == "__main__":
    main()