# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UMi2yJ-9MsG57FiJBrKV2IsDN0RXz2I7
"""

# Student Record System using Tuples and Sets

student_ids = (10, 200, 145, 23,)


print("Student IDs (unchangeable):")
for sid in student_ids:
    print(sid)

courses = {"Python", "AI", "ML"}

print("\nCurrent Courses:")
print(courses)

new_course = "Data Science"
courses.add(new_course)
print("\nAfter adding a course:")
print(courses)


courses.remove("ML")
print("\nAfter removing a course:")
print(courses)

courses.add("Python")
print("\nAfter trying to add duplicate 'Python':")
print(courses)