# -*- coding: utf-8 -*-
"""Task 6 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xHJHhHaIiFFABXKCQcGLyhCyunEnSy6j
"""

# Part 1: Score-to-Grade Evaluator
def evaluate_grade(score: float) -> str:
    if not 0 <= score <= 100:
        return "Invalid score. Must be between 0 and 100."

    if score >= 90:
        return "A"
    elif score >= 85:
        return "A-"
    elif score >= 80:
        return "B+"
    elif score >= 75:
        return "B"
    elif score >= 70:
        return "B-"
    elif score >= 65:
        return "C+"
    elif score >= 60:
        return "C"
    elif score >= 50:
        return "D"
    else:
        return "F"

def print_grade_summary(student_name: str = 'Unnamed', score: float = 0.0):
    grade = evaluate_grade(score)
    if "Invalid" in grade:
        print(f"Error: {grade}")
    else:
        print(f"Student {student_name} scored {score} → Grade: {grade}")


if __name__ == "__main__":
    name = input("Enter student name: ")
    try:
        score_input = float(input("Enter score (0–100): "))
        print_grade_summary(student_name=name, score=score_input)
    except ValueError:
        print("Invalid input. Please enter a numeric score.")