# -*- coding: utf-8 -*-
"""Task 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zhqe-AWYLZ5jRibNasrvufob9lHLu2Al
"""

def analyze_numbers(num_list):
    for i in range(len(num_list)):
        for j in range(0, len(num_list) - i - 1):
            if num_list[j] > num_list[j + 1]:
                num_list[j], num_list[j + 1] = num_list[j + 1], num_list[j]

    total = 0
    minimum = num_list[0]
    maximum = num_list[0]

    for num in num_list:
        total += num
        if num < minimum:
            minimum = num
        if num > maximum:
            maximum = num

    avg = total / len(num_list)

    result = {
        "sorted": num_list,
        "sum": total,
        "average": avg,
        "min": minimum,
        "max": maximum
    }

    return result


def print_dashboard(data):
    count = 1
    for key, value in data.items():
        print(f"{count}. {key} → {value}")
        count += 1


how_many = input("How many numbers? ")

while not how_many.isdigit():
    how_many = input("Please enter a valid number: ")

n = int(how_many)
nums = []

i = 0
while i < n:
    val = input(f"Enter number {i+1}: ")
    try:
        num = float(val)
        nums.append(num)
        i += 1
    except:
        print("Invalid input. Enter a number.")

stats = analyze_numbers(nums)
print_dashboard(stats)