# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y2-KA_GAU7gI-7F_TdOTWQOSz2G3Z1p9
"""

# Taking inputs from the user
int_input = int(input("Enter an integer: "))
float_input = float(input("Enter a float: "))
string_input = input("Enter a string: ")


print("\n--- Output ---")
print(f"Integer Value: {int_input}")
print(f"Float Value: {float_input}")
print(f"String Value: '{string_input}'")