# -*- coding: utf-8 -*-
"""Task14 capstone idea billEase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GPY1jxK5RZB-V6R5PJprCcvrmuEoMhdB
"""

# bill_splitter.py
import json
import os
from datetime import datetime

DATA_FILE = 'bills.json'

def load_data():
    if not os.path.exists(DATA_FILE):
        return []
    with open(DATA_FILE, 'r') as f:
        return json.load(f)

def save_data(data):
    with open(DATA_FILE, 'w') as f:
        json.dump(data, f, indent=2)

def add_bill():
    print("\n--- Add a New Bill ---")
    name = input("Bill Name (e.g., Electricity): ").strip()
    amount = float(input("Total Amount: Rs. "))
    num_people = int(input("Number of roommates: "))
    split = round(amount / num_people, 2)
    people = [input(f"Enter name of person #{i+1}: ").strip() for i in range(num_people)]

    entry = {
        'name': name,
        'amount': amount,
        'date': datetime.now().strftime("%Y-%m-%d"),
        'split_amount': split,
        'people': people
    }

    data = load_data()
    data.append(entry)
    save_data(data)

    print(f"\n Added: Rs. {amount} split among {', '.join(people)} (Rs. {split} each)")

def view_bills():
    print("\n Bill History:")
    data = load_data()
    if not data:
        print("No bills recorded yet.")
        return
    for idx, bill in enumerate(data, start=1):
        print(f"{idx}. {bill['name']} | Rs. {bill['amount']} | {bill['date']} | Shared by: {', '.join(bill['people'])}")

def main():
    while True:
        print("\nBillEase Menu")
        print("1. Add a Bill")
        print("2. View All Bills")
        print("3. Exit")
        choice = input("Choose an option (1-3): ").strip()
        if choice == '1':
            add_bill()
        elif choice == '2':
            view_bills()
        elif choice == '3':
            print("Goodbye")
            break
        else:
            print("Invalid option. Try again.")

if __name__ == "__main__":
    main()

